using System;
using System.Collections.Generic;
using Sim.Core.Config;
using Sim.Core.Domain;
using Sim.Core.Random;

namespace Sim.Core.Generation
{
    /// <summary>
    /// Builds the whole football world for a career (task 11.1): a real pyramid across many nations,
    /// loaded at the depth the player asked for.
    ///
    /// Determinism, which is the whole point:
    ///   • every stream is derived from (world seed, nation index, tier) alone — never from the loop
    ///     order, never from how many other nations happen to be loaded. A club generated in a Small
    ///     database is the same club, with the same id, in a Large one;
    ///   • ids come from <see cref="WorldIds"/>, which reserves a fixed block per (nation, tier);
    ///   • the naming pass runs once per nation on its own stream, so a nation's club names do not
    ///     shift when a tier below it is or isn't loaded.
    ///
    /// What it does NOT do: touch <see cref="LeagueGenerator"/>. The pre-11.1 two-division career is
    /// generated by exactly the same code as before, so every golden master and save still stands.
    /// </summary>
    public sealed class WorldGenerator
    {
        /// <summary>Odd constants giving each generation stream its own decorrelated seed.</summary>
        private const ulong NationSeedMix = 0x9E3779B185EBCA87UL;
        private const ulong NamingSequence = 9100UL;
        private const ulong SquadSequence = 9200UL;
        private const ulong NationalitySequence = 9300UL;
        private const ulong FixtureSequence = 9400UL;

        private readonly WorldGenerationOptions _options;
        private readonly BalanceConfig _config;
        private readonly GenerationBalance _gen;
        private readonly WorldBalance _world;
        private readonly DatabaseSizePreset _preset;

        public WorldGenerator(WorldGenerationOptions? options = null, BalanceConfig? config = null)
        {
            _options = options ?? new WorldGenerationOptions();
            _config = config ?? new BalanceConfig();
            _gen = _config.Generation;
            _world = _config.World;
            _preset = _options.ResolvePreset();
        }

        /// <summary>
        /// Generates the world. Same seed + same scope + same data ⇒ byte-identical world on every
        /// platform. Throws when the scope names a nation the atlas does not contain: a career must
        /// never silently start in a world other than the one the player picked.
        /// </summary>
        public World Generate(ulong seed)
        {
            ValidateScope();

            var world = new World
            {
                Scope = _options.Scope.Clone(),
                NextGeneratedPlayerId = WorldIds.FirstDynamicPlayerId
            };

            for (int index = 0; index < _options.Nations.Count; index++)
            {
                NationProfile profile = _options.Nations[index];
                Nation? nation = GenerateNation(index, profile, seed);
                if (nation != null)
                    world.Nations.Add(nation);
            }

            BuildBackgroundSeason(world, seed);
            return world;
        }

        private void ValidateScope()
        {
            foreach (PlayableNation playable in _options.Scope.Playable)
            {
                if (NationDatabase.Find(_options.Nations, playable.Code) == null)
                    throw new InvalidOperationException($"Scope names nation '{playable.Code}', which is not in the atlas.");

                if (playable.PlayableTiers < 1)
                    throw new InvalidOperationException($"Nation '{playable.Code}' is playable with {playable.PlayableTiers} tiers.");
            }
        }

        /// <summary>
        /// Decides how deep this nation is loaded and at what detail, then generates it.
        /// Returns null when the preset leaves it out of the world entirely.
        /// </summary>
        private Nation? GenerateNation(int index, NationProfile profile, ulong seed)
        {
            int available = profile.Divisions.Count;
            if (available == 0)
                return null;

            if (available > WorldIds.MaxTiersPerNation)
                throw new InvalidOperationException($"Nation '{profile.Code}' has {available} tiers; the id layout allows {WorldIds.MaxTiersPerNation}.");

            int playableTiers = _options.Scope.PlayableTiersOf(profile.Code);
            if (playableTiers > available)
                playableTiers = available;

            bool isPlayable = playableTiers > 0;
            if (!isPlayable && profile.Reputation < _preset.MinNationReputation)
                return null;

            LeagueDetailLevel extraLevel = profile.Reputation >= _preset.BackgroundMinReputation
                ? LeagueDetailLevel.Background
                : LeagueDetailLevel.DataOnly;

            int extraTiers = extraLevel == LeagueDetailLevel.Background
                ? _preset.BackgroundTiers
                : _preset.DataOnlyTiers;

            int totalTiers = playableTiers + extraTiers;
            if (totalTiers > available)
                totalTiers = available;

            if (totalTiers == 0)
                return null;

            var nation = new Nation
            {
                Id = index,
                Code = profile.Code,
                Name = profile.Name,
                Continent = profile.Continent,
                Reputation = profile.Reputation,
                CultureId = profile.CultureId
            };

            string[] clubNames = BuildClubNames(index, profile, seed);
            NameCulture? culture = ResolveCulture(profile);
            int nameCursor = 0;

            for (int tier = 1; tier <= totalTiers; tier++)
            {
                DivisionProfile division = profile.Divisions[tier - 1];
                LeagueDetailLevel level = tier <= playableTiers ? LeagueDetailLevel.Playable : extraLevel;

                League league = GenerateLeague(index, profile, division, tier, level, culture, clubNames, ref nameCursor, seed);
                nation.Leagues.Add(league);
            }

            return nation;
        }

        private League GenerateLeague(
            int nationIndex,
            NationProfile profile,
            DivisionProfile division,
            int tier,
            LeagueDetailLevel level,
            NameCulture? culture,
            string[] clubNames,
            ref int nameCursor,
            ulong seed)
        {
            if (division.ClubCount > WorldIds.MaxClubsPerTier)
                throw new InvalidOperationException($"'{profile.Code}' tier {tier} has {division.ClubCount} clubs; the id layout allows {WorldIds.MaxClubsPerTier}.");

            var league = new League
            {
                Id = WorldIds.LeagueId(nationIndex, tier),
                Name = $"{profile.Name} {division.Name}",
                Division = tier,
                NationCode = profile.Code,
                DetailLevel = level
            };

            int squadSize = SquadSizeFor(level);
            (PositionRole Role, int Count)[] template = SquadTemplate.For(squadSize);

            int actualSquad = 0;
            foreach (var (_, count) in template) actualSquad += count;

            if (division.ClubCount * actualSquad > WorldIds.MaxPlayersPerTier)
                throw new InvalidOperationException($"'{profile.Code}' tier {tier} needs {division.ClubCount * actualSquad} player ids; the layout allows {WorldIds.MaxPlayersPerTier}.");

            var squadRng = new Pcg32(NationSeed(seed, nationIndex), SquadSequence + (ulong)tier);
            var nationalityRng = new Pcg32(NationSeed(seed, nationIndex), NationalitySequence + (ulong)tier);

            var playerGenerator = new PlayerGenerator(_gen, culture);
            int firstClubId = WorldIds.FirstClubOf(nationIndex, tier);
            int nextPlayerId = WorldIds.FirstPlayerOf(nationIndex, tier);
            int keyPlayerBonus = level == LeagueDetailLevel.DataOnly ? _world.DataOnlyKeyPlayerBonus : 0;

            for (int c = 0; c < division.ClubCount; c++)
            {
                int jitter = _gen.ClubStrengthJitter;
                int baseline = ClubBaseline(profile, tier, c, division.ClubCount)
                               + squadRng.NextInt(-jitter, jitter + 1);
                baseline = AttributeScale.ClampSkill(baseline);

                string clubName = clubNames[nameCursor++ % clubNames.Length];

                var club = new Club
                {
                    Id = firstClubId + c,
                    Name = clubName,
                    ShortName = MakeShortName(clubName),
                    Strength = baseline,
                    Coach = new Coach
                    {
                        Id = firstClubId + c,
                        Name = $"{playerGenerator.FirstNames[squadRng.NextInt(0, playerGenerator.FirstNames.Length)]} " +
                               $"{playerGenerator.LastNames[squadRng.NextInt(0, playerGenerator.LastNames.Length)]}",
                        IsHuman = false,
                        Reputation = AttributeScale.ClampCondition(baseline)
                    }
                };

                var usedNames = new HashSet<string>();
                foreach (var (role, count) in template)
                {
                    for (int i = 0; i < count; i++)
                    {
                        int target = AttributeScale.ClampSkill(
                            baseline + keyPlayerBonus
                            + squadRng.NextInt(-_gen.PlayerTargetNoise, _gen.PlayerTargetNoise + 1));

                        Player player = playerGenerator.Generate(nextPlayerId++, role, target, squadRng);

                        int retries = 0;
                        while (!usedNames.Add(player.FullName) && retries++ < 20)
                        {
                            player.FirstName = playerGenerator.FirstNames[squadRng.NextInt(0, playerGenerator.FirstNames.Length)];
                            player.LastName = playerGenerator.LastNames[squadRng.NextInt(0, playerGenerator.LastNames.Length)];
                        }

                        player.Nationality = PickNationality(profile, nationalityRng);
                        club.Squad.Players.Add(player);
                    }
                }

                league.Clubs.Add(club);
            }

            return league;
        }

        private int SquadSizeFor(LeagueDetailLevel level)
        {
            switch (level)
            {
                case LeagueDetailLevel.Playable:
                    return SquadTemplate.TotalPlayers;
                case LeagueDetailLevel.Background:
                    return _preset.BackgroundSquadSize;
                default:
                    return _preset.DataOnlyPlayersPerClub;
            }
        }

        /// <summary>
        /// Linear spread from the nation's strongest club to its weakest, shifted down one
        /// DivisionStrengthStep per tier and up/down by the nation's reputation. A top club in a
        /// 100-reputation nation and one in a 50-reputation nation are twenty points apart, which is
        /// what makes scouting abroad worth doing.
        /// </summary>
        private int ClubBaseline(NationProfile profile, int tier, int clubIndex, int clubCount)
        {
            int nationOffset = (profile.Reputation - _world.ReputationPivot) * _world.StrengthPerReputationPoint / 10;
            int step = _gen.DivisionStrengthStep * (tier - 1);
            int top = _gen.TopClubStrength + nationOffset - step;
            int bottom = _gen.BottomClubStrength + nationOffset - step;

            if (clubCount <= 1)
                return top;

            return top - (top - bottom) * clubIndex / (clubCount - 1);
        }

        /// <summary>
        /// All the club names a nation will ever need, drawn once on the nation's own stream so they
        /// do not depend on how many of its tiers are loaded. Every prefix/town pair is used at most
        /// once, which is why 24 towns and 8 prefixes cover even a 68-club pyramid.
        /// </summary>
        private string[] BuildClubNames(int nationIndex, NationProfile profile, ulong seed)
        {
            NameCulture culture = ResolveCulture(profile) ?? FallbackCulture();

            int needed = 0;
            foreach (DivisionProfile division in profile.Divisions)
                needed += division.ClubCount;

            var pairs = new List<string>(culture.Towns.Length * culture.ClubPrefixes.Length);
            foreach (string town in culture.Towns)
            {
                foreach (string prefix in culture.ClubPrefixes)
                    pairs.Add($"{prefix} {town}");
            }

            var rng = new Pcg32(NationSeed(seed, nationIndex), NamingSequence);
            for (int i = pairs.Count - 1; i > 0; i--)
            {
                int j = rng.NextInt(0, i + 1);
                (pairs[i], pairs[j]) = (pairs[j], pairs[i]);
            }

            if (pairs.Count < needed)
                throw new InvalidOperationException($"Culture '{culture.Id}' offers {pairs.Count} club names; '{profile.Code}' needs {needed}.");

            return pairs.ToArray();
        }

        private NameCulture? ResolveCulture(NationProfile profile)
        {
            if (_options.Cultures != null
                && _options.Cultures.TryGetValue(profile.CultureId, out NameCulture? culture)
                && culture != null
                && culture.IsUsable)
            {
                return culture;
            }

            return null;
        }

        private static NameCulture FallbackCulture() => new NameCulture
        {
            Id = "fallback",
            FirstNames = NameDatabase.FirstNames,
            LastNames = NameDatabase.LastNames,
            Towns = NameDatabase.ClubTowns,
            ClubPrefixes = NameDatabase.ClubPrefixes
        };

        /// <summary>
        /// A player's nationality: mostly the nation he was generated in, otherwise an import. Strong
        /// leagues import far more than weak ones, and imports lean towards the same continent.
        /// Drawn on a stream of its own so adding it never perturbed the squad draw.
        /// </summary>
        private string PickNationality(NationProfile home, IRandomSource rng)
        {
            int foreignPercent = home.Reputation - _world.ForeignShareBase;
            if (foreignPercent < _world.ForeignShareMin) foreignPercent = _world.ForeignShareMin;
            if (foreignPercent > _world.ForeignShareMax) foreignPercent = _world.ForeignShareMax;

            if (rng.NextInt(0, 100) >= foreignPercent)
                return home.Code;

            bool sameContinent = rng.NextInt(0, 100) < _world.SameContinentForeignPercent;
            List<NationProfile> pool = sameContinent ? ContinentPool(home.Continent) : _options.Nations;

            if (pool.Count == 0)
                return home.Code;

            // Drawing the home nation out of the pool is fine: it just means this one stayed local.
            return pool[rng.NextInt(0, pool.Count)].Code;
        }

        private Dictionary<Continent, List<NationProfile>>? _continentPools;

        private List<NationProfile> ContinentPool(Continent continent)
        {
            if (_continentPools == null)
            {
                _continentPools = new Dictionary<Continent, List<NationProfile>>();
                foreach (NationProfile profile in _options.Nations)
                {
                    if (!_continentPools.TryGetValue(profile.Continent, out List<NationProfile>? list))
                    {
                        list = new List<NationProfile>();
                        _continentPools[profile.Continent] = list;
                    }

                    list.Add(profile);
                }
            }

            return _continentPools.TryGetValue(continent, out List<NationProfile>? pool)
                ? pool
                : new List<NationProfile>();
        }

        /// <summary>
        /// Fixtures for every BACKGROUND league, kept in the world's own season so the career day
        /// loop never walks them. Playable leagues are left alone: their fixtures belong to the
        /// career season the host builds, exactly as before 11.1.
        /// </summary>
        private void BuildBackgroundSeason(World world, ulong seed)
        {
            var generator = new FixtureGenerator(_config.Season);
            int nextFixtureId = 1;

            foreach (Nation nation in world.Nations)
            {
                foreach (League league in nation.Leagues)
                {
                    if (league.DetailLevel != LeagueDetailLevel.Background)
                        continue;

                    var rng = new Pcg32(NationSeed(seed, nation.Id), FixtureSequence + (ulong)league.Division);
                    List<Fixture> fixtures = generator.Generate(league, rng, nextFixtureId);
                    nextFixtureId += fixtures.Count;
                    world.BackgroundSeason.Fixtures.AddRange(fixtures);
                }
            }
        }

        private static ulong NationSeed(ulong seed, int nationIndex) =>
            seed ^ ((ulong)(nationIndex + 1) * NationSeedMix);

        private static string MakeShortName(string clubName)
        {
            int space = clubName.IndexOf(' ');
            string town = space >= 0 ? clubName.Substring(space + 1) : clubName;
            return (town.Length >= 3 ? town.Substring(0, 3) : town).ToUpperInvariant();
        }
    }
}
