// <auto-generated />
using System;
using Fts.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Fts.Infrastructure.Migrations
{
    [DbContext(typeof(FtsDbContext))]
    [Migration("20260723081948_AddRankedSeason")]
    partial class AddRankedSeason
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Fts.Infrastructure.Auth.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Fts.Infrastructure.Auth.CoachProfile", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.HasKey("UserId");

                    b.HasIndex("DisplayName");

                    b.ToTable("coach_profiles", (string)null);
                });

            modelBuilder.Entity("Fts.Infrastructure.Auth.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RevokedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("Fts.Infrastructure.Notifications.DeviceRegistration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastSeenUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Platform")
                        .HasColumnType("integer");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("device_registrations", (string)null);
                });

            modelBuilder.Entity("Fts.Infrastructure.Persistence.Entities.Auction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EndsUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("HighBid")
                        .HasColumnType("bigint");

                    b.Property<int?>("HighBidClubExternalId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("HighBidClubId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("HighBidUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PrivateLeagueId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("SettledUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("StartPrice")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("WindowIndex")
                        .HasColumnType("integer");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("PrivateLeagueId", "Status");

                    b.ToTable("auctions", (string)null);
                });

            modelBuilder.Entity("Fts.Infrastructure.Persistence.Entities.Bid", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("Amount")
                        .HasColumnType("bigint");

                    b.Property<Guid>("AuctionId")
                        .HasColumnType("uuid");

                    b.Property<int>("ClubExternalId")
                        .HasColumnType("integer");

                    b.Property<Guid>("ClubId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("PlacedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PrivateLeagueId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AuctionId");

                    b.HasIndex("PrivateLeagueId");

                    b.ToTable("bids", (string)null);
                });

            modelBuilder.Entity("Fts.Infrastructure.Persistence.Entities.Club", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("Balance")
                        .HasColumnType("bigint");

                    b.Property<int>("ExternalId")
                        .HasColumnType("integer");

                    b.Property<Guid>("LeagueId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<int>("Strength")
                        .HasColumnType("integer");

                    b.Property<long>("TransferBudget")
                        .HasColumnType("bigint");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LeagueId");

                    b.HasIndex("WorldId", "ExternalId")
                        .IsUnique();

                    b.ToTable("clubs", (string)null);
                });

            modelBuilder.Entity("Fts.Infrastructure.Persistence.Entities.Coach", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BoardConfidence")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ClubId")
                        .HasColumnType("uuid");

                    b.Property<int>("ExternalId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsHuman")
                        .HasColumnType("boolean");

                    b.Property<int>("LastFinishPosition")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("ObjectiveExpectedPosition")
                        .HasColumnType("integer");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("Reputation")
                        .HasColumnType("integer");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ClubId")
                        .IsUnique();

                    b.HasIndex("OwnerUserId");

                    b.HasIndex("WorldId", "ExternalId")
                        .IsUnique();

                    b.ToTable("coaches", (string)null);
                });

            modelBuilder.Entity("Fts.Infrastructure.Persistence.Entities.League", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Division")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorldId", "Division");

                    b.ToTable("leagues", (string)null);
                });

            modelBuilder.Entity("Fts.Infrastructure.Persistence.Entities.LeagueFixture", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AwayClubId")
                        .HasColumnType("uuid");

                    b.Property<int>("AwayGoals")
                        .HasColumnType("integer");

                    b.Property<int>("Day")
                        .HasColumnType("integer");

                    b.Property<Guid>("HomeClubId")
                        .HasColumnType("uuid");

                    b.Property<int>("HomeGoals")
                        .HasColumnType("integer");

                    b.Property<bool>("IsPlayed")
                        .HasColumnType("boolean");

                    b.Property<int>("MatchIndex")
                        .HasColumnType("integer");

                    b.Property<long>("MatchSeed")
                        .HasColumnType("bigint");

                    b.Property<Guid>("PrivateLeagueId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReplayJson")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ResolvedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Round")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AwayClubId");

                    b.HasIndex("HomeClubId");

                    b.HasIndex("PrivateLeagueId", "Round", "MatchIndex");

                    b.ToTable("league_fixtures", (string)null);
                });

            modelBuilder.Entity("Fts.Infrastructure.Persistence.Entities.LeagueLineup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClubId")
                        .HasColumnType("uuid");

                    b.Property<string>("LineupJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PrematchPlanJson")
                        .HasColumnType("text");

                    b.Property<Guid>("PrivateLeagueId")
                        .HasColumnType("uuid");

                    b.Property<string>("TacticJson")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ClubId");

                    b.HasIndex("PrivateLeagueId", "ClubId")
                        .IsUnique();

                    b.HasIndex("PrivateLeagueId", "UserId");

                    b.ToTable("league_lineups", (string)null);
                });

            modelBuilder.Entity("Fts.Infrastructure.Persistence.Entities.LeagueMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ClubId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsReady")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("JoinedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PrivateLeagueId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ClubId");

                    b.HasIndex("UserId");

                    b.HasIndex("PrivateLeagueId", "UserId")
                        .IsUnique();

                    b.ToTable("league_members", (string)null);
                });

            modelBuilder.Entity("Fts.Infrastructure.Persistence.Entities.LeagueTraining", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClubId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PrivateLeagueId")
                        .HasColumnType("uuid");

                    b.Property<string>("TrainingJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ClubId");

                    b.HasIndex("PrivateLeagueId", "ClubId")
                        .IsUnique();

                    b.HasIndex("PrivateLeagueId", "UserId");

                    b.ToTable("league_trainings", (string)null);
                });

            modelBuilder.Entity("Fts.Infrastructure.Persistence.Entities.LiveMatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AwayClubId")
                        .HasColumnType("uuid");

                    b.Property<int>("AwayGoals")
                        .HasColumnType("integer");

                    b.Property<bool>("AwayPresent")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("AwayUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("ChangesJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FinishedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FixtureId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("HomeClubId")
                        .HasColumnType("uuid");

                    b.Property<int>("HomeGoals")
                        .HasColumnType("integer");

                    b.Property<bool>("HomePresent")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("HomeUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("KickoffUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PrivateLeagueId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReportJson")
                        .HasColumnType("text");

                    b.Property<int>("Round")
                        .HasColumnType("integer");

                    b.Property<long>("Seed")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FixtureId")
                        .IsUnique();

                    b.HasIndex("PrivateLeagueId", "Status");

                    b.ToTable("live_matches", (string)null);
                });

            modelBuilder.Entity("Fts.Infrastructure.Persistence.Entities.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<string>("AttributesJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("ClubId")
                        .HasColumnType("uuid");

                    b.Property<int>("ContractSeasonsRemaining")
                        .HasColumnType("integer");

                    b.Property<int>("ExternalId")
                        .HasColumnType("integer");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<int>("Fitness")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(100);

                    b.Property<int>("Form")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(50);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<long>("MarketValue")
                        .HasColumnType("bigint");

                    b.Property<int>("Morale")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(50);

                    b.Property<int>("Overall")
                        .HasColumnType("integer");

                    b.Property<int>("Potential")
                        .HasColumnType("integer");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<long>("WeeklyWage")
                        .HasColumnType("bigint");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ClubId");

                    b.HasIndex("WorldId", "ExternalId")
                        .IsUnique();

                    b.ToTable("players", (string)null);
                });

            modelBuilder.Entity("Fts.Infrastructure.Persistence.Entities.PrivateLeague", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatorUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("InviteCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<int>("Mode")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("Size")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatorUserId");

                    b.HasIndex("InviteCode")
                        .IsUnique();

                    b.HasIndex("WorldId");

                    b.ToTable("private_leagues", (string)null);
                });

            modelBuilder.Entity("Fts.Infrastructure.Persistence.Entities.RankedCoach", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AutoEnrol")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("EnrolledUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("PlacedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("PlacementGroupId")
                        .HasColumnType("uuid");

                    b.Property<int?>("PlacementPosition")
                        .HasColumnType("integer");

                    b.Property<Guid>("RankedWorldId")
                        .HasColumnType("uuid");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<Guid?>("SeatId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.HasIndex("RankedWorldId", "Status");

                    b.ToTable("ranked_coaches", (string)null);
                });

            modelBuilder.Entity("Fts.Infrastructure.Persistence.Entities.RankedFixture", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AwayClubId")
                        .HasColumnType("uuid");

                    b.Property<int>("AwayGoals")
                        .HasColumnType("integer");

                    b.Property<int>("Day")
                        .HasColumnType("integer");

                    b.Property<Guid>("HomeClubId")
                        .HasColumnType("uuid");

                    b.Property<int>("HomeGoals")
                        .HasColumnType("integer");

                    b.Property<bool>("IsPlayed")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("KickoffUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MatchIndex")
                        .HasColumnType("integer");

                    b.Property<long>("MatchSeed")
                        .HasColumnType("bigint");

                    b.Property<Guid>("RankedGroupId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReplayJson")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ResolvedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Round")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AwayClubId");

                    b.HasIndex("HomeClubId");

                    b.HasIndex("RankedGroupId", "IsPlayed");

                    b.HasIndex("RankedGroupId", "Round", "MatchIndex")
                        .IsUnique();

                    b.ToTable("ranked_fixtures", (string)null);
                });

            modelBuilder.Entity("Fts.Infrastructure.Persistence.Entities.RankedGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GroupIndex")
                        .HasColumnType("integer");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<int>("LastMarketWindowOpened")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid>("RankedWorldId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("SeasonStartedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Tier")
                        .HasColumnType("integer");

                    b.Property<Guid?>("WorldId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorldId");

                    b.HasIndex("Kind", "Status");

                    b.HasIndex("RankedWorldId", "Kind", "Tier", "GroupIndex");

                    b.ToTable("ranked_groups", (string)null);
                });

            modelBuilder.Entity("Fts.Infrastructure.Persistence.Entities.RankedLineup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClubId")
                        .HasColumnType("uuid");

                    b.Property<string>("LineupJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PrematchPlanJson")
                        .HasColumnType("text");

                    b.Property<Guid>("RankedGroupId")
                        .HasColumnType("uuid");

                    b.Property<string>("TacticJson")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ClubId");

                    b.HasIndex("RankedGroupId", "ClubId")
                        .IsUnique();

                    b.HasIndex("RankedGroupId", "UserId");

                    b.ToTable("ranked_lineups", (string)null);
                });

            modelBuilder.Entity("Fts.Infrastructure.Persistence.Entities.RankedSeat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ClubId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("OccupiedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RankedGroupId")
                        .HasColumnType("uuid");

                    b.Property<int>("SeatIndex")
                        .HasColumnType("integer");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ClubId");

                    b.HasIndex("UserId");

                    b.HasIndex("RankedGroupId", "SeatIndex")
                        .IsUnique();

                    b.ToTable("ranked_seats", (string)null);
                });

            modelBuilder.Entity("Fts.Infrastructure.Persistence.Entities.RankedWorld", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("SeasonNumber")
                        .HasColumnType("integer");

                    b.Property<long>("Seed")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.ToTable("ranked_worlds", (string)null);
                });

            modelBuilder.Entity("Fts.Infrastructure.Persistence.Entities.Transfer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Day")
                        .HasColumnType("integer");

                    b.Property<long>("Fee")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("FromClubId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<int>("SeasonYear")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ToClubId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("WorldId", "SeasonYear", "Day");

                    b.ToTable("transfers", (string)null);
                });

            modelBuilder.Entity("Fts.Infrastructure.Persistence.Entities.World", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<long>("Seed")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("worlds", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("role_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("user_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("user_logins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("user_tokens", (string)null);
                });

            modelBuilder.Entity("Fts.Infrastructure.Auth.CoachProfile", b =>
                {
                    b.HasOne("Fts.Infrastructure.Auth.AppUser", "User")
                        .WithOne("Profile")
                        .HasForeignKey("Fts.Infrastructure.Auth.CoachProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Fts.Infrastructure.Auth.RefreshToken", b =>
                {
                    b.HasOne("Fts.Infrastructure.Auth.AppUser", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Fts.Infrastructure.Notifications.DeviceRegistration", b =>
                {
                    b.HasOne("Fts.Infrastructure.Auth.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Fts.Infrastructure.Persistence.Entities.Auction", b =>
                {
                    b.HasOne("Fts.Infrastructure.Persistence.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fts.Infrastructure.Persistence.Entities.PrivateLeague", "PrivateLeague")
                        .WithMany()
                        .HasForeignKey("PrivateLeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("PrivateLeague");
                });

            modelBuilder.Entity("Fts.Infrastructure.Persistence.Entities.Bid", b =>
                {
                    b.HasOne("Fts.Infrastructure.Persistence.Entities.Auction", "Auction")
                        .WithMany("Bids")
                        .HasForeignKey("AuctionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Auction");
                });

            modelBuilder.Entity("Fts.Infrastructure.Persistence.Entities.Club", b =>
                {
                    b.HasOne("Fts.Infrastructure.Persistence.Entities.League", "League")
                        .WithMany("Clubs")
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fts.Infrastructure.Persistence.Entities.World", "World")
                        .WithMany("Clubs")
                        .HasForeignKey("WorldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("League");

                    b.Navigation("World");
                });

            modelBuilder.Entity("Fts.Infrastructure.Persistence.Entities.Coach", b =>
                {
                    b.HasOne("Fts.Infrastructure.Persistence.Entities.Club", "Club")
                        .WithOne("Coach")
                        .HasForeignKey("Fts.Infrastructure.Persistence.Entities.Coach", "ClubId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Fts.Infrastructure.Persistence.Entities.World", "World")
                        .WithMany("Coaches")
                        .HasForeignKey("WorldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Club");

                    b.Navigation("World");
                });

            modelBuilder.Entity("Fts.Infrastructure.Persistence.Entities.League", b =>
                {
                    b.HasOne("Fts.Infrastructure.Persistence.Entities.World", "World")
                        .WithMany("Leagues")
                        .HasForeignKey("WorldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("World");
                });

            modelBuilder.Entity("Fts.Infrastructure.Persistence.Entities.LeagueFixture", b =>
                {
                    b.HasOne("Fts.Infrastructure.Persistence.Entities.Club", "AwayClub")
                        .WithMany()
                        .HasForeignKey("AwayClubId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fts.Infrastructure.Persistence.Entities.Club", "HomeClub")
                        .WithMany()
                        .HasForeignKey("HomeClubId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fts.Infrastructure.Persistence.Entities.PrivateLeague", "PrivateLeague")
                        .WithMany()
                        .HasForeignKey("PrivateLeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AwayClub");

                    b.Navigation("HomeClub");

                    b.Navigation("PrivateLeague");
                });

            modelBuilder.Entity("Fts.Infrastructure.Persistence.Entities.LeagueLineup", b =>
                {
                    b.HasOne("Fts.Infrastructure.Persistence.Entities.Club", "Club")
                        .WithMany()
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fts.Infrastructure.Persistence.Entities.PrivateLeague", "PrivateLeague")
                        .WithMany()
                        .HasForeignKey("PrivateLeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Club");

                    b.Navigation("PrivateLeague");
                });

            modelBuilder.Entity("Fts.Infrastructure.Persistence.Entities.LeagueMember", b =>
                {
                    b.HasOne("Fts.Infrastructure.Persistence.Entities.Club", "Club")
                        .WithMany()
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Fts.Infrastructure.Persistence.Entities.PrivateLeague", "PrivateLeague")
                        .WithMany("Members")
                        .HasForeignKey("PrivateLeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Club");

                    b.Navigation("PrivateLeague");
                });

            modelBuilder.Entity("Fts.Infrastructure.Persistence.Entities.LeagueTraining", b =>
                {
                    b.HasOne("Fts.Infrastructure.Persistence.Entities.Club", "Club")
                        .WithMany()
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fts.Infrastructure.Persistence.Entities.PrivateLeague", "PrivateLeague")
                        .WithMany()
                        .HasForeignKey("PrivateLeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Club");

                    b.Navigation("PrivateLeague");
                });

            modelBuilder.Entity("Fts.Infrastructure.Persistence.Entities.LiveMatch", b =>
                {
                    b.HasOne("Fts.Infrastructure.Persistence.Entities.PrivateLeague", "PrivateLeague")
                        .WithMany()
                        .HasForeignKey("PrivateLeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PrivateLeague");
                });

            modelBuilder.Entity("Fts.Infrastructure.Persistence.Entities.Player", b =>
                {
                    b.HasOne("Fts.Infrastructure.Persistence.Entities.Club", "Club")
                        .WithMany("Players")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Fts.Infrastructure.Persistence.Entities.World", "World")
                        .WithMany("Players")
                        .HasForeignKey("WorldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Club");

                    b.Navigation("World");
                });

            modelBuilder.Entity("Fts.Infrastructure.Persistence.Entities.PrivateLeague", b =>
                {
                    b.HasOne("Fts.Infrastructure.Persistence.Entities.World", "World")
                        .WithMany()
                        .HasForeignKey("WorldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("World");
                });

            modelBuilder.Entity("Fts.Infrastructure.Persistence.Entities.RankedCoach", b =>
                {
                    b.HasOne("Fts.Infrastructure.Persistence.Entities.RankedWorld", "RankedWorld")
                        .WithMany()
                        .HasForeignKey("RankedWorldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RankedWorld");
                });

            modelBuilder.Entity("Fts.Infrastructure.Persistence.Entities.RankedFixture", b =>
                {
                    b.HasOne("Fts.Infrastructure.Persistence.Entities.Club", "AwayClub")
                        .WithMany()
                        .HasForeignKey("AwayClubId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fts.Infrastructure.Persistence.Entities.Club", "HomeClub")
                        .WithMany()
                        .HasForeignKey("HomeClubId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fts.Infrastructure.Persistence.Entities.RankedGroup", "RankedGroup")
                        .WithMany()
                        .HasForeignKey("RankedGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AwayClub");

                    b.Navigation("HomeClub");

                    b.Navigation("RankedGroup");
                });

            modelBuilder.Entity("Fts.Infrastructure.Persistence.Entities.RankedGroup", b =>
                {
                    b.HasOne("Fts.Infrastructure.Persistence.Entities.RankedWorld", "RankedWorld")
                        .WithMany("Groups")
                        .HasForeignKey("RankedWorldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fts.Infrastructure.Persistence.Entities.World", "World")
                        .WithMany()
                        .HasForeignKey("WorldId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("RankedWorld");

                    b.Navigation("World");
                });

            modelBuilder.Entity("Fts.Infrastructure.Persistence.Entities.RankedLineup", b =>
                {
                    b.HasOne("Fts.Infrastructure.Persistence.Entities.Club", "Club")
                        .WithMany()
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fts.Infrastructure.Persistence.Entities.RankedGroup", "RankedGroup")
                        .WithMany()
                        .HasForeignKey("RankedGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Club");

                    b.Navigation("RankedGroup");
                });

            modelBuilder.Entity("Fts.Infrastructure.Persistence.Entities.RankedSeat", b =>
                {
                    b.HasOne("Fts.Infrastructure.Persistence.Entities.Club", "Club")
                        .WithMany()
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Fts.Infrastructure.Persistence.Entities.RankedGroup", "RankedGroup")
                        .WithMany("Seats")
                        .HasForeignKey("RankedGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Club");

                    b.Navigation("RankedGroup");
                });

            modelBuilder.Entity("Fts.Infrastructure.Persistence.Entities.Transfer", b =>
                {
                    b.HasOne("Fts.Infrastructure.Persistence.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fts.Infrastructure.Persistence.Entities.World", "World")
                        .WithMany("Transfers")
                        .HasForeignKey("WorldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("World");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Fts.Infrastructure.Auth.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Fts.Infrastructure.Auth.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fts.Infrastructure.Auth.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Fts.Infrastructure.Auth.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Fts.Infrastructure.Auth.AppUser", b =>
                {
                    b.Navigation("Profile");

                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("Fts.Infrastructure.Persistence.Entities.Auction", b =>
                {
                    b.Navigation("Bids");
                });

            modelBuilder.Entity("Fts.Infrastructure.Persistence.Entities.Club", b =>
                {
                    b.Navigation("Coach");

                    b.Navigation("Players");
                });

            modelBuilder.Entity("Fts.Infrastructure.Persistence.Entities.League", b =>
                {
                    b.Navigation("Clubs");
                });

            modelBuilder.Entity("Fts.Infrastructure.Persistence.Entities.PrivateLeague", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("Fts.Infrastructure.Persistence.Entities.RankedGroup", b =>
                {
                    b.Navigation("Seats");
                });

            modelBuilder.Entity("Fts.Infrastructure.Persistence.Entities.RankedWorld", b =>
                {
                    b.Navigation("Groups");
                });

            modelBuilder.Entity("Fts.Infrastructure.Persistence.Entities.World", b =>
                {
                    b.Navigation("Clubs");

                    b.Navigation("Coaches");

                    b.Navigation("Leagues");

                    b.Navigation("Players");

                    b.Navigation("Transfers");
                });
#pragma warning restore 612, 618
        }
    }
}
