// <auto-generated />
using System;
using Fts.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Fts.Infrastructure.Migrations
{
    [DbContext(typeof(FtsDbContext))]
    partial class FtsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Fts.Infrastructure.Persistence.Entities.Club", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("Balance")
                        .HasColumnType("bigint");

                    b.Property<int>("ExternalId")
                        .HasColumnType("integer");

                    b.Property<Guid>("LeagueId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<int>("Strength")
                        .HasColumnType("integer");

                    b.Property<long>("TransferBudget")
                        .HasColumnType("bigint");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LeagueId");

                    b.HasIndex("WorldId", "ExternalId")
                        .IsUnique();

                    b.ToTable("clubs", (string)null);
                });

            modelBuilder.Entity("Fts.Infrastructure.Persistence.Entities.Coach", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BoardConfidence")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ClubId")
                        .HasColumnType("uuid");

                    b.Property<int>("ExternalId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsHuman")
                        .HasColumnType("boolean");

                    b.Property<int>("LastFinishPosition")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("ObjectiveExpectedPosition")
                        .HasColumnType("integer");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("Reputation")
                        .HasColumnType("integer");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ClubId")
                        .IsUnique();

                    b.HasIndex("OwnerUserId");

                    b.HasIndex("WorldId", "ExternalId")
                        .IsUnique();

                    b.ToTable("coaches", (string)null);
                });

            modelBuilder.Entity("Fts.Infrastructure.Persistence.Entities.League", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Division")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorldId", "Division");

                    b.ToTable("leagues", (string)null);
                });

            modelBuilder.Entity("Fts.Infrastructure.Persistence.Entities.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<string>("AttributesJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("ClubId")
                        .HasColumnType("uuid");

                    b.Property<int>("ContractSeasonsRemaining")
                        .HasColumnType("integer");

                    b.Property<int>("ExternalId")
                        .HasColumnType("integer");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<long>("MarketValue")
                        .HasColumnType("bigint");

                    b.Property<int>("Overall")
                        .HasColumnType("integer");

                    b.Property<int>("Potential")
                        .HasColumnType("integer");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<long>("WeeklyWage")
                        .HasColumnType("bigint");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ClubId");

                    b.HasIndex("WorldId", "ExternalId")
                        .IsUnique();

                    b.ToTable("players", (string)null);
                });

            modelBuilder.Entity("Fts.Infrastructure.Persistence.Entities.Transfer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Day")
                        .HasColumnType("integer");

                    b.Property<long>("Fee")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("FromClubId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<int>("SeasonYear")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ToClubId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("WorldId", "SeasonYear", "Day");

                    b.ToTable("transfers", (string)null);
                });

            modelBuilder.Entity("Fts.Infrastructure.Persistence.Entities.World", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<long>("Seed")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("worlds", (string)null);
                });

            modelBuilder.Entity("Fts.Infrastructure.Persistence.Entities.Club", b =>
                {
                    b.HasOne("Fts.Infrastructure.Persistence.Entities.League", "League")
                        .WithMany("Clubs")
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fts.Infrastructure.Persistence.Entities.World", "World")
                        .WithMany("Clubs")
                        .HasForeignKey("WorldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("League");

                    b.Navigation("World");
                });

            modelBuilder.Entity("Fts.Infrastructure.Persistence.Entities.Coach", b =>
                {
                    b.HasOne("Fts.Infrastructure.Persistence.Entities.Club", "Club")
                        .WithOne("Coach")
                        .HasForeignKey("Fts.Infrastructure.Persistence.Entities.Coach", "ClubId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Fts.Infrastructure.Persistence.Entities.World", "World")
                        .WithMany("Coaches")
                        .HasForeignKey("WorldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Club");

                    b.Navigation("World");
                });

            modelBuilder.Entity("Fts.Infrastructure.Persistence.Entities.League", b =>
                {
                    b.HasOne("Fts.Infrastructure.Persistence.Entities.World", "World")
                        .WithMany("Leagues")
                        .HasForeignKey("WorldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("World");
                });

            modelBuilder.Entity("Fts.Infrastructure.Persistence.Entities.Player", b =>
                {
                    b.HasOne("Fts.Infrastructure.Persistence.Entities.Club", "Club")
                        .WithMany("Players")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Fts.Infrastructure.Persistence.Entities.World", "World")
                        .WithMany("Players")
                        .HasForeignKey("WorldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Club");

                    b.Navigation("World");
                });

            modelBuilder.Entity("Fts.Infrastructure.Persistence.Entities.Transfer", b =>
                {
                    b.HasOne("Fts.Infrastructure.Persistence.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fts.Infrastructure.Persistence.Entities.World", "World")
                        .WithMany("Transfers")
                        .HasForeignKey("WorldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("World");
                });

            modelBuilder.Entity("Fts.Infrastructure.Persistence.Entities.Club", b =>
                {
                    b.Navigation("Coach");

                    b.Navigation("Players");
                });

            modelBuilder.Entity("Fts.Infrastructure.Persistence.Entities.League", b =>
                {
                    b.Navigation("Clubs");
                });

            modelBuilder.Entity("Fts.Infrastructure.Persistence.Entities.World", b =>
                {
                    b.Navigation("Clubs");

                    b.Navigation("Coaches");

                    b.Navigation("Leagues");

                    b.Navigation("Players");

                    b.Navigation("Transfers");
                });
#pragma warning restore 612, 618
        }
    }
}
